# Generated by Django 4.2.7 on 2023-12-02 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_todo_author_alter_todo_todo_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='author',
        ),
    ]
