# Generated by Django 4.2.7 on 2023-12-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_todolist_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='todo_list',
        ),
    ]
